### PR TITLE
Creating a lookup file for -w

### PR DESCRIPTION
**Pull request by Luca0208**
This will make it easier for people to see what -w option they should use. If everyone puts his/her values in this will save some time for other persons so they don't need to trial and error.

### CODE REVIEW

**Comment by apemanzilla** [comment]
Not a bad idea, but the worksize values vary significantly depending on manufacturer, clock speeds, operating system, etc. For example, on a GTX 760 on Windows 10, I was reaching 160 MH/s. However, by simply rebooting to Ubuntu, I was easily passing 230 MH/s with the same worksize.

I have plans to implement a system profiler (similar to the one used in my origin project, [JCLMiner](https://github.com/apemanzilla/JCLMiner/blob/master/src/main/java/me/apemanzilla/jclminer/SystemProfiler.java)) but hopefully less crashy.

**Comment by apemanzilla** [comment]
By the way, if you'd like to add this as a wiki page, you're more than welcome to.

**Comment by Luca0208** [comment]
Well I didn't know that it various per operating system. A wiki page wouldn't make sense then, right?

**Comment by apemanzilla** [comment]
A wiki page could at least be used to provide expected speeds for people setting it up.

**Comment by Luca0208** [comment]
ok, but I have no idea how to create a wiki page xD

**Comment by Luca0208** [comment]
Ok, I checked only people with write access can.

**Comment by apemanzilla** [comment]
You should be able to create a wiki page now.

**Pull request closed without merging**
